---
- name: Install Docker SDK for Python
  pip:
    name: docker
    state: present

- name: Pull Metabase Docker image
  docker_image:
    name: metabase/metabase
    tag: latest
    state: present

- name: Run Metabase Docker container
  docker_container:
    name: metabase
    image: metabase/metabase:latest
    state: started
    ports:
      - "3000:3000"
    detach: yes
