---
- name: Install Docker
  apt:
    name:
      - docker.io
      - containerd
      - runc
    state: present

- name: Add "ubuntu" user to "docker" group
  user:
    name: ubuntu
    groups: docker
    append: yes

- block:
    - name: install docker Compose
      shell: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
